components/ruby/chef-licensing.gemspec
Set License ID string in gemspec to select LICENSE file
This doesn't change the LICENSE - which remains Proprietary at this time - but it does correct the gem build, so that the gem build system properly can find the custom license file.
=> Set License ID string in gemspec to select LICENSE file

components/ruby/lib/chef-licensing/license_key_fetcher.rb, components/ruby/lib/chef-licensing/license_key_fetcher/chef_licensing_interactions.yaml, components/ruby/spec/chef_licensing_ux_spec.rb
This PR introduces the change in the UI text to display unit measure as target or node depending upon the product name.
**CHEF-3768: Display Target or Node as the unit measure depending upon the Chef Product (UI/UX Change)**
=> CHEF-3768: Display Target or Node as the unit measure depending upon the Chef Product (UI/UX Change)

.expeditor/config.yml
This PR updates the config to be able to publish the chef-licensing gems to rubygems on promote.
**CHEF-4068: Modify chef-licensing expeditor config to publish to rubygems on promote**
=> CHEF-4068: Modify expeditor config to publish to rubygems on promote

components/ruby/lib/chef-licensing/exceptions/invalid_file_format_version.rb, components/ruby/lib/chef-licensing/license_key_fetcher/file.rb, components/ruby/spec/chef-licensing/license_key_fetcher/file_spec.rb, components/ruby/spec/list_license_keys_spec.rb
This PR introduces the change to raise a new exception class viz. `InvalidFileFormatVersion` when an unsupported licenses.yaml is present in the system. It helps the application using the chef-licensing library to raise appropriate error message.
Given a system has the following licenses.yaml file
```
❯ cat ~/.chef/licenses.yaml
---
:file_format_version: 3.0.0
:license_server_url: https://licensing-acceptance.chef.co/License
:licenses:
- :license_key: free-00000000-111b-4cb2-a7f3-ab2222d025d7-999
:license_type: :free
:update_time: '2023-07-10T15:08:25+05:30'
```
The current behavior of InSpec with an unsupported licenses.yaml on the system is as below:
```
❯ bundle exec inspec exec
[2023-07-10T15:08:44+05:30] ERROR: Chef InSpec cannot execute without valid licenses.
```
The behavior of …
=> CHEF-3843: Update exception class for invalid file format version of licenses.yaml

components/ruby/lib/chef-licensing/restful_client/base.rb, components/ruby/lib/chef-licensing/restful_client/middleware/exceptions_handler.rb, components/ruby/spec/restful_client_v1_spec.rb
This PR adds support for using multiple license server URLs. The implementation works by trying each URL until a reachable server URL is found. The reachable URL is then updated in the Config to be used for the duration of the program's execution.
To specify the multiple license server URLs, you can either provide them as comma-separated values using an argument or set them as environment variables.
Example: 
`export CHEF_LICENSE_SERVER=http://localhost-1-license-server/License,http://localhost-2-license-server/License`
or
`--chef-license-server=http://localhost-1-license-server/License,http://localhost-2-license-server/License`
**CHEF-4087: Support multiple license server URL in chef licensing**
=> CHEF-4087: Feature support multiple license server URLs 

components/ruby/lib/chef-licensing/tui_engine/tui_actions.rb, components/ruby/spec/chef-licensing/tui_engine/tui_actions_spec.rb
This PR updates the regex for the company name validation:
- to accept upto 20 characters length
- to accept space between the company name (two worded company like Progress Chef was not getting accepted)
- to not let the company name start with space
=> Update regex for company name validation

components/ruby/lib/chef-licensing/exceptions/license_file_corrupted.rb, components/ruby/lib/chef-licensing/license_key_fetcher/file.rb, components/ruby/lib/chef-licensing/license_key_fetcher/license_file/base.rb, components/ruby/lib/chef-licensing/license_key_fetcher/license_file/v3.rb, components/ruby/lib/chef-licensing/license_key_fetcher/license_file/v4.rb, components/ruby/spec/chef-licensing/license_key_fetcher/file_spec.rb, components/ruby/spec/fixtures/license_file_without_file_format_version/licenses.yaml, components/ruby/spec/fixtures/licenses.yaml, components/ruby/spec/fixtures/multiple_license_keys_license/licenses.yaml, components/ruby/spec/fixtures/v3_licenses/licenses.yaml
This PR introduces the backward compatibility handling of version 3.0.0 licenses.yaml files and provides the basic structure of how we would support future versions with minimal changes to the codebase.
**CHEF-3841: chef-licensing licenses.yaml loading not backward compatible**
=> CHEF-3841: Handle different versions of `licenses.yaml` file [Backward Compatibility Support]

components/ruby/lib/chef-licensing/restful_client/base.rb, components/ruby/lib/chef-licensing/restful_client/v1.rb
This PR introduces application-level caching of the API responses by using the cache manager i.e. `ChefLicensing::RestfulClient::CacheManager`.
It maintains a list of the endpoints which we would like to cache. The list can be extended or the condition can be removed if we desire to cache for all the endpoints.
[CHEF-3961: Ability to cache based on per license basis and not at the network level](https://chefio.atlassian.net/browse/CHEF-3961)
=> Enable caching of API response at the application-level

components/ruby/lib/chef-licensing.rb, components/ruby/lib/chef-licensing/api/client.rb, components/ruby/lib/chef-licensing/restful_client/base.rb, components/ruby/spec/restful_client_v1_spec.rb
This PR introduces an endpoint in the base class of restful client which can be used by the specific api classes like client to clear cache of their respective endpoints.
Note: The classes invoking the `clear_cache` needs to send two parameters: `endpoint` and the params which they send to call their respective endpoints in the base class. This is required to form the cache key for deletion.
=> CACHE: Implement the ability to clear the cache by invoking `clear_cache` in base

components/ruby/lib/chef-licensing/license_key_fetcher.rb
This is follow-up missing change on PR #127
In Local licensing mode also, we needed error handling for the license expiration check
This check was missed.
This check makes sure that any `/client` error encountered is not raised from this point, but let the software entitlement check that will happen again after this call to handle all these errors.
=> Local licensing mode - Error handling for license expiration check

components/ruby/lib/chef-licensing/license_key_fetcher/chef_licensing_interactions.yaml, components/ruby/spec/chef_licensing_ux_spec.rb
This PR enhances the user experience to be able to provide a license id when the user follows either the free or trial license generation journey in the cli.
Additionally, it updates the web link for free/trial license generation. 
```
...
We have the following types of licenses.
Select the type of license below and then enter user details
1. Free License
Validity: Unlimited
No. of units: 10 targets
! Kindly complete the user registration at https://www.chef.io/licensing/inspec/license-genertation-free-trial
Once you submit the details, you will receive the license ID on the email id you provided.
Select an option (Press ↑/↓ arrow to move and Enter to select)
‣ Validate license now
Quit and validate license later
```
This is to eliminate the hassle for the user to quit the process and add …
=> CHEF-5997 & CHEF-5919: Replace license generation UI with link to web form

components/ruby/Gemfile.lock, components/ruby/chef-licensing.gemspec
The latest version of `ActiveSupport` i.e. `[7.1.0](https://rubygems.org/gems/activesupport/versions/7.1.0) - October 05, 2023 (250 KB)` has some issue with setting the default config to use its cache_format_version as 7.1.0 and picks 6.1 instead by default.
This leads to a deprecation warning when using ActiveSupport Cache in our Faraday connection. Hence, until the ActiveSupport gem has a stable release and the issue is fixed, we continue to use the 7.0.x versions of ActiveSupport in our library.
```
DEPRECATION WARNING: Support for `config.active_support.cache_format_version = 6.1` has been deprecated and will be removed in Rails 7.2.
Check the Rails upgrade guide at https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#new-activesupport-cache-serialization-format
for more …
```
=> Add constraint to ActiveSupport gem to use version lower than 7.1

components/ruby/lib/chef-licensing/exceptions/unsupported_content_type.rb, components/ruby/lib/chef-licensing/restful_client/base.rb, components/ruby/lib/chef-licensing/restful_client/middleware/content_type_validator.rb, components/ruby/spec/restful_client_v1_spec.rb
This PR implements content-type validation for server responses. The Chef Licensing library requires an 'application/json' content type response for all its APIs.
With this handling when the server return's a non json type content it gives the error as shown below:
```
❯ bundle exec inspec exec
[2023-12-01T18:09:43+05:30] ERROR: Expected 'application/json' content-type, but received 'text/plain; charset=utf-8' from the licensing server.
Snippet of body: `This is a test page for the dummy server!`
Possible causes: Check for firewall restrictions, ensure proper server response, or seek support assistance.
```
CHEF-8798: Validate server's response content-type to ensure functionality or display appropriate error messages
=> CHEF-8798: Validate server's response content-type to ensure functionality or display appropriate error messages

components/ruby/lib/chef-licensing/license.rb, components/ruby/lib/chef-licensing/license_key_fetcher.rb, components/ruby/lib/chef-licensing/license_key_fetcher/chef_licensing_interactions.yaml, components/ruby/lib/chef-licensing/tui_engine/tui_actions.rb, components/ruby/spec/chef_licensing_ux_spec.rb, components/ruby/spec/fixtures/api_response_data/exhausted_commercial_client_api_response.json, components/ruby/spec/license_key_fetcher_spec.rb
This PR implements the functionality and the UI to display when the target limit is exceeded for licenses available on the system.
CHEF-4925: Show a license enforcement message when a commercial user exceeds the purchased target limit
=> CHEF-4925: Show a license enforcement message on exceeding target limit for commercial license

components/ruby/lib/chef-licensing/license_key_fetcher.rb, components/ruby/lib/chef-licensing/license_key_fetcher/chef_licensing_interactions.yaml, components/ruby/lib/chef-licensing/tui_engine/tui_actions.rb, components/ruby/spec/chef_licensing_ux_spec.rb, components/ruby/spec/fixtures/api_response_data/exhausted_free_client_api_response.json, components/ruby/spec/license_key_fetcher_spec.rb
This PR implements the functionality and the UI to display when the target limit is exceeded for free licenses available on the system
CHEF-4924: Show a license enforcement message when a free tier user exceeds the purchased target
=> CHEF-4924: Show a license enforcement message on exceeding target limit for free license

.expeditor/verify.pipeline.yml
CHEF-11234: CI is breaking for inspec, inspec-gcp, and train due to issue with docker image used for the tests
=> CHEF-11234: update ruby base image to bullseye

components/ruby/lib/chef-licensing.rb, components/ruby/lib/chef-licensing/context.rb, components/ruby/lib/chef-licensing/license_key_fetcher.rb, components/ruby/spec/chef-licensing/context_spec.rb, components/ruby/spec/chef_licensing_ux_spec.rb
License context caching and fetching to enable:
1. Caching license context via fetch and persist when license context is available
2. Ability to fetch license context if available or to fetch the fresh context via API call using license keys.
=> CHEF-7258 License context caching and fetching

components/ruby/lib/chef-licensing/license_key_fetcher/chef_licensing_interactions.yaml, components/ruby/spec/chef_licensing_ux_spec.rb
This PR updates the message for trial license users upon expiry. Additionally, it adjusts the flow to exit the execution in case of an expired license.
CHEF-10500: Update message for trial license users upon expiry
=> CHEF-10500: Update message for trial license users upon expiry

components/ruby/lib/chef-licensing/license_key_fetcher.rb, components/ruby/lib/chef-licensing/license_key_fetcher/chef_licensing_interactions.yaml, components/ruby/lib/chef-licensing/tui_engine/tui_actions.rb, components/ruby/spec/chef_licensing_ux_spec.rb, components/ruby/spec/license_key_fetcher_spec.rb
This PR introduces a method which displays a warning message for non-commercial users.
CHEF-10498: Modify CLI reporter to show message regarding licensing to free and trial users
=> CHEF-10498: Add method to invoke warn message for non-commercial users

components/ruby/lib/chef-licensing/license_key_fetcher.rb, components/ruby/spec/chef_licensing_ux_spec.rb, components/ruby/spec/license_key_fetcher_spec.rb
Hard enforcement enabled - when a license is expired. Raises error.
- No hard enforcement when a license is in grace status
- No hard enforcement when a license is about to expire.
**DO NOT MERGE:
This change is for post-release and will only be merged at a much later date based on business requirement.**
=> CHEF-4150 Hard enforcement enabled - when license expired

.expeditor/verify.pipeline.yml, components/ruby/chef-licensing.gemspec
Removes Ruby v3.0 support from chef-licensing
=> Remove ruby 3.0 support from chef-licensing

components/ruby/lib/chef-licensing/config.rb, components/ruby/lib/chef-licensing/license_key_fetcher/chef_licensing_interactions.yaml
This PR makes the license list and license add command texts dynamic allowing applications to display customized help messages for these commands.
This is done to achieve product neutral message.
CHEF-12730: Verify Messaging is Product Neutral
=> CHEF-12730: make license list & license add cmds as dynamic text

components/ruby/lib/chef-licensing/license_key_fetcher.rb, components/ruby/lib/chef-licensing/license_key_fetcher/file.rb, components/ruby/spec/fixtures/api_response_data/valid_client_api_response.json, components/ruby/spec/license_key_fetcher_spec.rb
Hard enforcement fix: Adding the same type of license using argument or env.
- If the user already has an expired trial license. After that, if the user tries to add an active trial license via argument `--chef-license-key` or via env variables `CHEF_LICENSE_KEY` it lets the user continue using InSpec. While it should enforce the user.
- If the user already has an exhausted free license. After that, if the user tries to add an active free license via argument `--chef-license-key` or via env variables `CHEF_LICENSE_KEY` it lets the user continue using InSpec. While it should enforce the user.
- ## Related Issue
=> CHEF-14142 Hard enforcement fix: Adding the same type of license

components/ruby/lib/chef-licensing/license_key_fetcher.rb, components/ruby/spec/license_key_fetcher_spec.rb
The chef-licensing library raises an exception of LicenseKeyNotFetchedError.new("Unable to obtain a License Key.") when the license key is about to expire or in grace period and is set in the environment of a non-interactive terminal i.e. the output stream is not a tty.
CHEF-14423: Fix `LicenseKeyNotFetchedError.new("Unable to obtain a License Key.")` occurring when the license key is set in the environment in a non-interactive environment
=> CHEF-14423: Fix LicenseKeyNotFetchedError in non-tty terminal with non-active license key

components/ruby/lib/chef-licensing.rb, components/ruby/spec/chef_licensing_spec.rb
This PR enhances the `fetch_and_persist` method to specifically handle entitlement errors. 
If a `ChefLicensing::ClientError` indicates a lack of entitlement, the method now raises a `ChefLicensing::SoftwareNotEntitled` exception. Other errors are re-raised as before.
=> Improve entitlement error handling during `fetch_and_persist`

.expeditor/verify.pipeline.yml, components/ruby/Gemfile, components/ruby/chef-licensing.gemspec, components/ruby/spec/chef-licensing/license_spec.rb
Adding support for Ruby 3.4. Upgraded few gem versions which also support Ruby 3.4
=> CHEF-20397 Ruby 3.4 support

components/ruby/lib/chef-licensing.rb, components/ruby/spec/chef_licensing_spec.rb, components/ruby/spec/chef_licensing_ux_spec.rb, components/ruby/spec/license_key_fetcher_spec.rb
Skip license entitlement check when licensing is optional
This change updates the logic to bypass the entitlement checks when 
ChefLicensing::Config.make_licensing_optional is true.
=> CHEF-25725 - Add Optional mode conditions for Software & Feature Entitlement checks

components/ruby/chef-licensing.gemspec
We are pinning the version of Faraday to ensure compatibility with InSpec. InSpec has a dependency on the `ms_rest_azure` gem, which only supports faraday `<= 2`. Without this pinning, independent packaging (such as with Habitat and chef official gem) could pull in newer Faraday versions that are incompatible.
=> Faraday pinning - enable compatibility with packaging gems in hab packages
